In [24]:
import pandas as pd
from bs4 import BeautifulSoup as bs
from splinter import Browser

In [25]:
csv_file = "resources/realdonaldtrump.csv"
trump_tweets_df = pd.read_csv(csv_file)
trump_tweets_df

,id,link,content,date,retweets,favorites,mentions,hashtags
0,1698308935,https://twitter.com/realDonaldTrump/status/169...,Be sure to tune in and watch Donald Trump on L...,2009-05-04 13:54:25,510,917,NaN,NaN
1,1701461182,https://twitter.com/realDonaldTrump/status/170...,Donald Trump will be appearing on The View tom...,2009-05-04 20:00:10,34,267,NaN,NaN
2,1737479987,https://twitter.com/realDonaldTrump/status/173...,Donald Trump reads Top Ten Financial Tips on L...,2009-05-08 08:38:08,13,19,NaN,NaN
3,1741160716,https://twitter.com/realDonaldTrump/status/174...,New Blog Post: Celebrity Apprentice Finale and...,2009-05-08 15:40:15,11,26,NaN,NaN
4,1773561338,https://twitter.com/realDonaldTrump/status/177...,"""My persona will never be that of a wallflower...",2009-05-12 09:07:28,1375,1945,NaN,NaN
...,...,...,...,...,...,...,...,...
43347,1273405198698975232,https://twitter.com/realDonaldTrump/status/127...,Joe Biden was a TOTAL FAILURE in Government. H...,2020-06-17 19:00:32,23402,116377,NaN,NaN
43348,1273408026968457216,https://twitter.com/realDonaldTrump/status/127...,Will be interviewed on @ seanhannity tonight a...,2020-06-17 19:11:47,11810,56659,@seanhannity,NaN
43349,1273442195161387008,https://twitter.com/realDonaldTrump/status/127...,pic.twitter.com/3lm1spbU8X,2020-06-17 21:27:33,4959,19344,NaN,NaN
43350,1273442469066276864,https://twitter.com/realDonaldTrump/status/127...,pic.twitter.com/vpCE5MadUz,2020-06-17 21:28:38,4627,17022,NaN,NaN
43351,1273442528411385858,https://twitter.com/realDonaldTrump/status/127...,pic.twitter.com/VLlc0BHW41,2020-06-17 21:28:52,3951,14344,NaN,NaN

In [ ]:
# Use Splinter to scrape the 2009-2020 calendar

# Set the path and create browser
# executable_path = {'executable_path': 'chromedriver.exe'}
# browser = Browser('chrome', **executable_path, headless=False)

In [52]:
base_url = "https://www.timeanddate.com/holidays/us/"

In [53]:
calendar = []

In [54]:
for x in range (2009, 2021):
    url2 = (f'{base_url}{x}')
    tables = pd.read_html(url2)
    df = tables[0]
    df["Year"] = x
    calendar.append(df)

calendar

[                                                  Date  \
                                                   Date
 0                                                Jan 1
 1                                                Jan 6
 2                                                Jan 7
 3                                                Jan 7
 4                                               Jan 13
 ..                                                 ...
 350                                             Dec 25
 351                                             Dec 26
 352                                             Dec 26
 353                                             Dec 31
 354  * Observed only in part of this state. ** Obse...

                                     Unnamed: 1_level_0  \
                                     Unnamed: 1_level_1
 0                                             Thursday
 1                                              Tuesday
 2                                            Wednesday
 3                                            Wednesday
 4                                              Tuesday
 ..                                                 ...
 350                                             Friday
 351                                           Saturday
 352                                           Saturday
 353                                           Thursday
 354  * Observed only in part of this state. ** Obse...

                                                   Name  \
                                                   Name
 0                                       New Year's Day
 1                                             Epiphany
 2                               Orthodox Christmas Day
 3                       International Programmers' Day
 4                          Stephen Foster Memorial Day
 ..                                                 ...
 350                                      Christmas Day
 351                                Kwanzaa (first day)
 352                            Day After Christmas Day
 353                                     New Year's Eve
 354  * Observed only in part of this state. ** Obse...

                                                   Type  \
                                                   Type
 0                                      Federal Holiday
 1                                            Christian
 2                                             Orthodox
 3                                 Worldwide observance
 4                                           Observance
 ..                                                 ...
 350                                    Federal Holiday
 351                                         Observance
 352                                      State holiday
 353                                         Observance
 354  * Observed only in part of this state. ** Obse...

                                                Details  Year
                                                Details
 0                                                  NaN  2009
 1                                                  NaN  2009
 2                                                  NaN  2009
 3                                                  NaN  2009
 4                                                  NaN  2009
 ..                                                 ...   ...
 350                                                NaN  2009
 351                                                NaN  2009
 352                                              Texas  2009
 353                                                NaN  2009
 354  * Observed only in part of this state. ** Obse...  2009

 [355 rows x 6 columns],
                                                   Date  \
                                                   Date
 0                                                Jan 1
 1                                                Jan 6
 2                                                Jan 7
 3                                                Jan 7
 4                                               Jan 13
 ..                                                 ...
 361                                             Dec 26
 362                                             Dec 26
 363                                             Dec 31
 364                                             Dec 31
 365  * Observed only in part of this state. ** Obse...

                                     Unnamed: 1_level_0  \
                                     Unnamed: 1_level_1
 0                                               Friday
 1                                            Wednesday
 2                                             Thursday
 3                                             Thursday
 4                                            Wednesday
 ..                                                 ...
 361                                             Sunday
 362                                             Sunday
 363                                             Friday
 364                                             Friday
 365  * Observed only in part of this state. ** Obse...

                                                   Name  \
                                                   Name
 0                                       New Year's Day
 1                                             Epiphany
 2                               Orthodox Christmas Day
 3                       International Programmers' Day
 4                          Stephen Foster Memorial Day
 ..                                                 ...
 361                                Kwanzaa (first day)
 362                            Day After Christmas Day
 363                            New Year's Day observed
 364                                     New Year's Eve
 365  * Observed only in part of this state. ** Obse...

                                                   Type  \
                                                   Type
 0                                      Federal Holiday
 1                                            Christian
 2                                             Orthodox
 3                                 Worldwide observance
 4                                           Observance
 ..                                                 ...
 361                                         Observance
 362                                      State holiday
 363                                    Federal Holiday
 364                                         Observance
 365  * Observed only in part of this state. ** Obse...

                                                Details  Year
                                                Details
 0                                                  NaN  2010
 1                                                  NaN  2010
 2                                                  NaN  2010
 3                                                  NaN  2010
 4                                                  NaN  2010
 ..                                                 ...   ...
 361                                                NaN  2010
 362                                              Texas  2010
 363                                                NaN  2010
 364                                                NaN  2010
 365  * Observed only in part of this state. ** Obse...  2010

 [366 rows x 6 columns],
                                                   Date  \
                                                   Date
 0                                                Jan 1
 1                                                Jan 6
 2                                                Jan 7
 3                                                Jan 7
 4                                               Jan 13
 ..                                                 ...
 376                                             Dec 26
 377                                             Dec 26
 378                                             Dec 28
 379                                             Dec 31
 380  * Observed only in some communities of this st...

                                     Unnamed: 1_level_0  \
                                     Unnamed: 1_level_1
 0                                             Saturday
 1                                             Thursday
 2                                               Friday
 3                                               Friday
 4                                             Thursday
 ..                                                 ...
 376                                             Monday
 377                                             Monday
 378                                          Wednesday
 379                                           Saturday
 380  * Observed only in some communities of this st...

                                                   Name  \
                                                   Name
 0                                       New Year's Day
 1                                             Epiphany
 2                               Orthodox Christmas Day
 3                       International Programmers' Day
 4                          Stephen Foster Memorial Day
 ..                                                 ...
 376                             Christmas Day observed
 377                            Day After Christmas Day
 378                               Last Day of Chanukah
 379                                     New Year's Eve
 380  * Observed only in some communities of this st...

                                                   Type  \
                                                   Type
 0                                      Federal Holiday
 1                                            Christian
 2                                             Orthodox
 3                                 Worldwide observance
 4                                           Observance
 ..                                                 ...
 376                                    Federal Holiday
 377                                      State holiday
 378                                     Jewish holiday
 379                                         Observance
 380  * Observed only in some communities of this st...

                                                Details  Year
                                                Details
 0                                                  NaN  2011
 1                                                  NaN  2011
 2                                                  NaN  2011
 3                                                  NaN  2011
 4                                                  NaN  2011
 ..                                                 ...   ...
 376                                                NaN  2011
 377                                              Texas  2011
 378                                                NaN  2011
 379                                                NaN  2011
 380  * Observed only in some communities of this st...  2011

 [381 rows x 6 columns],
                                                   Date  \
                                                   Date
 0                                                Jan 1
 1                                                Jan 2
 2                                                Jan 6
 3                                                Jan 7
 4                                                Jan 7
 ..                                                 ...
 387                                             Dec 26
 388                                             Dec 26
 389                                             Dec 31
 390                                             Dec 31
 391  * Observed only in part of this state. ** Obse...

                                     Unnamed: 1_level_0  \
                                     Unnamed: 1_level_1
 0                                               Sunday
 1                                               Monday
 2                                               Friday
 3                                             Saturday
 4                                             Saturday
 ..                                                 ...
 387                                          Wednesday
 388                                          Wednesday
 389                                             Monday
 390                                             Monday
 391  * Observed only in part of this state. ** Obse...

                                                   Name  \
                                                   Name
 0                                       New Year's Day
 1                              New Year's Day observed
 2                                             Epiphany
 3                               Orthodox Christmas Day
 4                       International Programmers' Day
 ..                                                 ...
 387                                Kwanzaa (first day)
 388                            Day After Christmas Day
 389                                     New Year's Eve
 390                                     New Year's Eve
 391  * Observed only in part of this state. ** Obse...

                                                   Type  \
                                                   Type
 0                                      Federal Holiday
 1                                      Federal Holiday
 2                                            Christian
 3                                             Orthodox
 4                                 Worldwide observance
 ..                                                 ...
 387                                         Observance
 388                                      State holiday
 389                                      State holiday
 390                                         Observance
 391  * Observed only in part of this state. ** Obse...

                                                Details  Year
                                                Details
 0                                                  NaN  2012
 1                                                  NaN  2012
 2                                                  NaN  2012
 3                                                  NaN  2012
 4                                                  NaN  2012
 ..                                                 ...   ...
 387                                                NaN  2012
 388                                              Texas  2012
 389                                          Wisconsin  2012
 390                                                NaN  2012
 391  * Observed only in part of this state. ** Obse...  2012

 [392 rows x 6 columns],
                                                   Date  \
                                                   Date
 0                                                Jan 1
 1                                                Jan 4
 2                                                Jan 6
 3                                                Jan 7
 4                                                Jan 7
 ..                                                 ...
 393                                             Dec 26
 394                                             Dec 26
 395                                             Dec 31
 396                                             Dec 31
 397  * Observed only in some communities of this st...

                                     Unnamed: 1_level_0  \
                                     Unnamed: 1_level_1
 0                                              Tuesday
 1                                               Friday
 2                                               Sunday
 3                                               Monday
 4                                               Monday
 ..                                                 ...
 393                                           Thursday
 394                                           Thursday
 395                                            Tuesday
 396                                            Tuesday
 397  * Observed only in some communities of this st...

                                                   Name  \
                                                   Name
 0                                       New Year's Day
 1                                    World Braille Day
 2                                             Epiphany
 3                               Orthodox Christmas Day
 4                       International Programmers' Day
 ..                                                 ...
 393                                Kwanzaa (first day)
 394                            Day After Christmas Day
 395                                     New Year's Eve
 396                                     New Year's Eve
 397  * Observed only in some communities of this st...

                                                   Type  \
                                                   Type
 0                                      Federal Holiday
 1                                 Worldwide observance
 2                                            Christian
 3                                             Orthodox
 4                                 Worldwide observance
 ..                                                 ...
 393                                         Observance
 394                                      State holiday
 395                                      State holiday
 396                                         Observance
 397  * Observed only in some communities of this st...

                                                Details  Year
                                                Details
 0                                                  NaN  2013
 1                                                  NaN  2013
 2                                                  NaN  2013
 3                                                  NaN  2013
 4                                                  NaN  2013
 ..                                                 ...   ...
 393                                                NaN  2013
 394                                     KS, NC, SC, TX  2013
 395                                         KY, MI, WI  2013
 396                                                NaN  2013
 397  * Observed only in some communities of this st...  2013

 [398 rows x 6 columns],
                                                   Date  \
                                                   Date
 0                                                Jan 1
 1                                                Jan 4
 2                                                Jan 6
 3                                                Jan 7
 4                                                Jan 7
 ..                                                 ...
 408                                             Dec 26
 409                                             Dec 26
 410                                             Dec 31
 411                                             Dec 31
 412  * Observed only in some communities of this st...

                                     Unnamed: 1_level_0  \
                                     Unnamed: 1_level_1
 0                                            Wednesday
 1                                             Saturday
 2                                               Monday
 3                                              Tuesday
 4                                              Tuesday
 ..                                                 ...

In [57]:
df = calendar[2]
df

,Date,Unnamed: 1_level_0,Name,Type,Details,Year
,Date,Unnamed: 1_level_1,Name,Type,Details,
0,Jan 1,Saturday,New Year's Day,Federal Holiday,NaN,2011
1,Jan 6,Thursday,Epiphany,Christian,NaN,2011
2,Jan 7,Friday,Orthodox Christmas Day,Orthodox,NaN,2011
3,Jan 7,Friday,International Programmers' Day,Worldwide observance,NaN,2011
4,Jan 13,Thursday,Stephen Foster Memorial Day,Observance,NaN,2011
...,...,...,...,...,...,...
376,Dec 26,Monday,Christmas Day observed,Federal Holiday,NaN,2011
377,Dec 26,Monday,Day After Christmas Day,State holiday,Texas,2011
378,Dec 28,Wednesday,Last Day of Chanukah,Jewish holiday,NaN,2011
379,Dec 31,Saturday,New Year's Eve,Observance,NaN,2011
380,* Observed only in some communities of this st...,* Observed only in some communities of this st...,* Observed only in some communities of this st...,* Observed only in some communities of this st...,* Observed only in some communities of this st...,2011