In [1]:
# Import Modules
import pandas as pd

In [2]:
# Import CSV file
csv_file = "resources/realdonaldtrump.csv"
realdonaldtrump_df = pd.read_csv(csv_file)

In [3]:
# Split date column into Day, Month, Year and Time
realdonaldtrump_df[['Date','Time']] = realdonaldtrump_df.date.str.split(" ",expand=True,)
realdonaldtrump_df[['Year','Month', 'Day']] = realdonaldtrump_df.Date.str.split("-",expand=True,)
realdonaldtrump_df.head()

,id,link,content,date,retweets,favorites,mentions,hashtags,Date,Time,Year,Month,Day
0,1698308935,https://twitter.com/realDonaldTrump/status/169...,Be sure to tune in and watch Donald Trump on L...,2009-05-04 13:54:25,510,917,NaN,NaN,2009-05-04,13:54:25,2009,05,04
1,1701461182,https://twitter.com/realDonaldTrump/status/170...,Donald Trump will be appearing on The View tom...,2009-05-04 20:00:10,34,267,NaN,NaN,2009-05-04,20:00:10,2009,05,04
2,1737479987,https://twitter.com/realDonaldTrump/status/173...,Donald Trump reads Top Ten Financial Tips on L...,2009-05-08 08:38:08,13,19,NaN,NaN,2009-05-08,08:38:08,2009,05,08
3,1741160716,https://twitter.com/realDonaldTrump/status/174...,New Blog Post: Celebrity Apprentice Finale and...,2009-05-08 15:40:15,11,26,NaN,NaN,2009-05-08,15:40:15,2009,05,08
4,1773561338,https://twitter.com/realDonaldTrump/status/177...,"""My persona will never be that of a wallflower...",2009-05-12 09:07:28,1375,1945,NaN,NaN,2009-05-12,09:07:28,2009,05,12

In [4]:
# Creating new trump tweets data frame
trump_tweets_df = realdonaldtrump_df[['id', 'link', 'content', 'retweets', 'favorites', 'mentions', 'hashtags', 'Date', 'Time', 'Year', 'Month', 'Day']]
trump_tweets_df.head()

,id,link,content,retweets,favorites,mentions,hashtags,Date,Time,Year,Month,Day
0,1698308935,https://twitter.com/realDonaldTrump/status/169...,Be sure to tune in and watch Donald Trump on L...,510,917,NaN,NaN,2009-05-04,13:54:25,2009,05,04
1,1701461182,https://twitter.com/realDonaldTrump/status/170...,Donald Trump will be appearing on The View tom...,34,267,NaN,NaN,2009-05-04,20:00:10,2009,05,04
2,1737479987,https://twitter.com/realDonaldTrump/status/173...,Donald Trump reads Top Ten Financial Tips on L...,13,19,NaN,NaN,2009-05-08,08:38:08,2009,05,08
3,1741160716,https://twitter.com/realDonaldTrump/status/174...,New Blog Post: Celebrity Apprentice Finale and...,11,26,NaN,NaN,2009-05-08,15:40:15,2009,05,08
4,1773561338,https://twitter.com/realDonaldTrump/status/177...,"""My persona will never be that of a wallflower...",1375,1945,NaN,NaN,2009-05-12,09:07:28,2009,05,12